### ISSUE TITLE
How to get more proposals

### ISSUE THREAD

**Issue by jiuerbujie** [kmaninis/COB#5]
Hi,
Thank you very much to release the code. I found that the number of proposals is smaller than EdgeBox. Is is possible to generate more proposals than your pre-computed ones? May I change some parameters to achieve this purpose? If so, which parameters are the most relevant ?
Thanks

**Comment by kmaninis** [comment]
Hi,
Thanks for your interest.
The easiest way to increase the number of proposals would be to increase J_th in the file im2prop.m. This will keep proposals which overlap more with each other.
The hard way would be to choose another point in the Pareto curve. For this, there is code in the MCG repo which may need some adjustment: https://github.com/jponttuset/mcg/blob/master/full/scripts_training/pareto_choose_point.m

I would personally go with option 1, since it is way easier.
Hope it helps :)
